{% set version = "1.1.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gensa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GenSA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GenSA/GenSA_{{ version }}.tar.gz
  sha256: 375e87541eb6b098584afccab361dc28ff09d03cf1d062ff970208e294eca216

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('GenSA')"           # [not win]
    - "\"%R%\" -e \"library('GenSA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GenSA
  license: GPL-2.0-only
  summary: Performs search for global minimum of a very complex non-linear objective function with a very large number of optima.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - lucapinello

# Package: GenSA
# Type: Package
# Title: Generalized Simulated Annealing
# Version: 1.1.7
# Date: 2018-01-15
# Author: Sylvain Gubian, Yang Xiang, Brian Suomela, Julia Hoeng, PMP SA.
# Maintainer: Sylvain Gubian <DL.RSupport@pmi.com>
# Depends: R (>= 2.12.0)
# Description: Performs search for global minimum of a very complex non-linear objective function with a very large number of optima.
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: yes
# Repository: CRAN
# RoxygenNote: 5.0.1
# Packaged: 2018-01-17 07:56:50 UTC; sgubian
# Date/Publication: 2018-01-17 15:02:35 UTC
